export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const FETCH_DATA_START="FETCH_DATA_START";
export const FETCH_DATA_END="FETCH_DATA_END";


export const CREATE_COLLECTION="CREATE_COLLECTION";
export const UPDATE_COLLECTION="UPDATE_COLELCTION";
export const DELETE_COLLECTION="DELETE_COLLECTION";
export const GET_ALL_COLLECTION="GET_ALL_COLLECTION";
export const GET_COLLECTION_BY_USER="GET_COLLECTION_BY_USER";
export const UPDATE_USER_PROFILE="UPDATE_USER_PROFILE";


export const CREATE_COLLECTION_FAIL="CREATE_COLLECTION_FAIL";
export const UPDATE_COLLECTION_FAIL="UPDATE_COLELCTION_FAIL";
export const DELETE_COLLECTION_FAIL="DELETE_COLLECTION_FAIL";
export const GET_ALL_COLLECTION_FAIL="GET_ALL_COLLECTION_FAIL";
export const GET_COLLECTION_BY_USER_FAIL="GET_COLLECTION_BY_USER_FAIL";
export const UPDATE_USER_PROFILE_FAIL="UPDATE_USER_PROFILE_FAIL";
